{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a425a28",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install aiogram aiosqlite apscheduler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5ac014b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import asyncio\n",
    "from aiogram import Bot, Dispatcher, types\n",
    "from aiogram.filters import Command\n",
    "import aiosqlite\n",
    "from datetime import datetime, timedelta\n",
    "from apscheduler.schedulers.asyncio import AsyncIOScheduler\n",
    "\n",
    "TOKEN = \"8774071198:AAEZ0baDm2bj6cUhLzBWU6PQkJS4j2kBMfI\"\n",
    "\n",
    "bot = Bot(token=TOKEN)\n",
    "dp = Dispatcher()\n",
    "scheduler = AsyncIOScheduler()\n",
    "\n",
    "# --- БАЗА ДАННЫХ ---\n",
    "async def init_db():\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        await db.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS books (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            title TEXT,\n",
    "            author TEXT,\n",
    "            status TEXT,\n",
    "            user_id INTEGER,\n",
    "            deadline TEXT\n",
    "        )\n",
    "        \"\"\")\n",
    "        await db.commit()\n",
    "\n",
    "# --- ДОБАВИТЬ КНИГИ ---\n",
    "async def seed_books():\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        books = await db.execute(\"SELECT COUNT(*) FROM books\")\n",
    "        count = (await books.fetchone())[0]\n",
    "\n",
    "        if count == 0:\n",
    "            await db.executemany(\"\"\"\n",
    "            INSERT INTO books (title, author, status)\n",
    "            VALUES (?, ?, 'free')\n",
    "            \"\"\", [\n",
    "                (\"1984\", \"George Orwell\"),\n",
    "                (\"The Hobbit\", \"J.R.R. Tolkien\"),\n",
    "                (\"Crime and Punishment\", \"Dostoevsky\")\n",
    "            ])\n",
    "            await db.commit()\n",
    "\n",
    "# --- СПИСОК КНИГ ---\n",
    "@dp.message(Command(\"books\"))\n",
    "async def show_books(message: types.Message):\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        cursor = await db.execute(\"SELECT id, title, author, status FROM books\")\n",
    "        books = await cursor.fetchall()\n",
    "\n",
    "    text = \"📚 Список книг:\\n\\n\"\n",
    "    for b in books:\n",
    "        status = \"✅ Свободна\" if b[3] == \"free\" else \"❌ Занята\"\n",
    "        text += f\"{b[0]}. {b[1]} — {b[2]} ({status})\\n\"\n",
    "\n",
    "    await message.answer(text)\n",
    "\n",
    "# --- БРОНЬ ---\n",
    "@dp.message(Command(\"reserve\"))\n",
    "async def reserve_book(message: types.Message):\n",
    "    try:\n",
    "        book_id = int(message.text.split()[1])\n",
    "    except:\n",
    "        await message.answer(\"Используй: /reserve ID\")\n",
    "        return\n",
    "\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        cursor = await db.execute(\"SELECT status FROM books WHERE id=?\", (book_id,))\n",
    "        book = await cursor.fetchone()\n",
    "\n",
    "        if not book:\n",
    "            await message.answer(\"Книга не найдена\")\n",
    "            return\n",
    "\n",
    "        if book[0] == \"taken\":\n",
    "            await message.answer(\"❌ Уже занята\")\n",
    "            return\n",
    "\n",
    "        deadline = datetime.now() + timedelta(days=7)\n",
    "\n",
    "        await db.execute(\"\"\"\n",
    "        UPDATE books\n",
    "        SET status='taken', user_id=?, deadline=?\n",
    "        WHERE id=?\n",
    "        \"\"\", (message.from_user.id, deadline.isoformat(), book_id))\n",
    "\n",
    "        await db.commit()\n",
    "\n",
    "    await message.answer(f\"✅ Забронировано до {deadline.date()}\")\n",
    "\n",
    "# --- ВОЗВРАТ ---\n",
    "@dp.message(Command(\"return\"))\n",
    "async def return_book(message: types.Message):\n",
    "    try:\n",
    "        book_id = int(message.text.split()[1])\n",
    "    except:\n",
    "        await message.answer(\"Используй: /return ID\")\n",
    "        return\n",
    "\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        await db.execute(\"\"\"\n",
    "        UPDATE books\n",
    "        SET status='free', user_id=NULL, deadline=NULL\n",
    "        WHERE id=?\n",
    "        \"\"\", (book_id,))\n",
    "        await db.commit()\n",
    "\n",
    "    await message.answer(\"📖 Книга возвращена\")\n",
    "\n",
    "# --- ПРОВЕРКА ДЕДЛАЙНОВ ---\n",
    "async def check_deadlines():\n",
    "    async with aiosqlite.connect(\"books.db\") as db:\n",
    "        cursor = await db.execute(\"\"\"\n",
    "        SELECT id, user_id, deadline FROM books\n",
    "        WHERE status='taken'\n",
    "        \"\"\")\n",
    "        books = await cursor.fetchall()\n",
    "\n",
    "    now = datetime.now()\n",
    "\n",
    "    for b in books:\n",
    "        deadline = datetime.fromisoformat(b[2])\n",
    "        diff = (deadline - now).days\n",
    "\n",
    "        # Напоминание за 1 день\n",
    "        if diff == 1:\n",
    "            await bot.send_message(b[1], f\"⏰ Завтра дедлайн книги ID {b[0]}\")\n",
    "\n",
    "        # Просрочка\n",
    "        if deadline < now:\n",
    "            async with aiosqlite.connect(\"books.db\") as db:\n",
    "                await db.execute(\"\"\"\n",
    "                UPDATE books\n",
    "                SET status='free', user_id=NULL, deadline=NULL\n",
    "                WHERE id=?\n",
    "                \"\"\", (b[0],))\n",
    "                await db.commit()\n",
    "\n",
    "            await bot.send_message(b[1], f\"❗ Срок истёк. Книга ID {b[0]} освобождена\")\n",
    "\n",
    "# --- СТАРТ ---\n",
    "async def main():\n",
    "    await init_db()\n",
    "    await seed_books()\n",
    "\n",
    "    scheduler.add_job(check_deadlines, \"interval\", hours=1)\n",
    "    scheduler.start()\n",
    "\n",
    "    print(\"Бот запущен...\")\n",
    "    await dp.start_polling(bot)\n",
    "\n",
    "await main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cfe09a22",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
